[package]
name = "navigator"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29"
egui = "0.29"
egui_dock = "0.14"
egui_extras = "0.29"
rusqlite = { version = "0.32", features = ["bundled"] }
rfd = "0.14"
